env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "lesha"

#написать &env::CONFIG_PATH=./logger/local.yaml в терминал